words = [
    "bufnr",
    "clangd",
    "ctermbg",
    "expandtab",
    "guibg",
    "hrsh",
    "lspconfig",
    "mapleader",
    "munif",
    "neotree",
    "nvim",
    "nvimtools",
    "pyright",
    "rafamadriz",
    "relativenumber",
    "saadparwaiz",
    "shiftwidth",
    "signcolumn",
    "softtabstop",
    "tabstop",
    "tanjim",
    "vscode",
    "williamboman",
]
